name: taskly_bloc_sqlite
description: "Taskly is a basic task manager app built using Flutter, 
              BLoC for state management, and SQLite for local storage. 
              It helps users add, edit, delete, and manage their daily tasks with ease."

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  flutter_slidable: ^3.1.0
  lottie: ^3.1.0
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mockito: ^5.4.2


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Animation_2.json

